[package]
name = "pythonize"
version = "0.1.0"
authors = ["David Hewitt <1939362+davidhewitt@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
description = "Serde Serializer & Deserializer from Rust <--> Python, backed by PyO3."
homepage = "https://github.com/davidhewitt/pythonize"
repository = "https://github.com/davidhewitt/pythonize"
documentation = "https://docs.rs/crate/pythonize/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0" }
pyo3 = { version = "0.11.1", default-features = false }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
paste = "1.0"
serde_json = "1.0"
maplit = "1.0.2"
