[package]
name = "pythonize"
version = "0.1.0"
authors = ["David Hewitt <1939362+davidhewitt@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0" }
pyo3 = { git = "https://github.com/pyo3/pyo3", default-features = false }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
